"""
Executor module for BEHAVIOR task execution.

This module provides executors that interface with Omnigibson/BEHAVIOR simulation
to execute task plans generated by LLM planners.

Key features:
- Detailed execution feedback for dynamic replanning
- Error categorization (object_not_found, grasp_failed, etc.)
- State tracking (object in hand, execution history)
"""

from .behavior_executor import (
    BehaviorExecutor,
    ActionFeedback,
    ExecutionErrorType
)

try:
    from .behavior_action_api import BehaviorActionAPI, StarterSemanticActionPrimitiveSet
    
    __all__ = [
        "BehaviorExecutor",
        "ActionFeedback",
        "ExecutionErrorType",
        "BehaviorActionAPI",
        "StarterSemanticActionPrimitiveSet",
    ]
except ImportError:
    # omnigibson not available - provide minimal exports
    __all__ = [
        "BehaviorExecutor",
        "ActionFeedback", 
        "ExecutionErrorType"
    ]
